version: '2'
services:
  mysql:
    image: percona:latest
    environment:
      MYSQL_ROOT_PASSWORD: $DOCKER_MYSQL_PASSWORD
    ports:
      - $DOCKER_MYSQL_LOCAL_PORT:3306
    networks:
      - lesara-coding-test_php-erp-test
  php-fpm:
    build:
      context: .docker/php-fpm
      args:
        LOCAL_USER_ID: $DOCKER_LOCAL_USER_ID
        LOCAL_GROUP_ID: $DOCKER_LOCAL_USER_GROUP
    user: $DOCKER_LOCAL_USER_ID:$DOCKER_LOCAL_USER_GROUP
    volumes:
      - ./:/var/www
    networks:
      - lesara-coding-test_php-erp-test
  nginx:
    build:
      context: .docker/nginx
    ports:
      - $DOCKER_NGINX_LOCAL_PORT:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lesara-coding-test_php-erp-test
networks:
  lesara-coding-test_php-erp-test:
    driver: bridge
